/** All in-game text is English. */
export const STR = {
  title: 'Crown & Clash',
  round: 'Round',
  victory: 'Victory',
  defeat: 'Defeat',
  pickAugment: 'Choose an Augment',
  chooseChampion: 'Choose your Champion',
  shopTitle: 'The Merchant',
  shopContinue: 'On to the Round',
  shopBought: 'Bought ✓',
  life: 'Life',
  usurpatorComes: 'The Usurper approaches…',
  crownIsYours: 'The Crown is yours!',
  retry: 'Try Again',
  lifeLost: '−1 Life — the arena calls the next round',
  finalMustFall: 'The Usurper must fall! Once more…',
  start: 'Begin Battle',
  runFlavor: 'Exiled. Betrayed. Yet the crown calls you back to the arena.',
  bossFlavorMini: 'The Usurper steps into the sand himself — he wants to watch you break.',
  bossFlavorFinal: 'The final battle. The Usurper wears your crown — take it from him.',
  defeatFlavor: 'The arena swallows another name. Yours fades away.',
  victoryFlavor: 'The throne is yours again. The arena cheers its king.',
  trainingHint: 'Training dummy — move with stick or WASD',
} as const;
